### ISSUE TITLE
Error:  __init__() got an unexpected keyword argument 'method'

### ISSUE THREAD

**Issue by rerouted** [bensquire/Digital-Ocean-Dynamic-DNS-Updater#11]
I know you are not really support but what might be the cause of this method error?  Using (updater-v2.py) script and v2 API Key.

Updating  sub . domain.com : 2015-04-20 08:50:42.622694
Fetching external IP from: http://checkip.dyndns.org:8245/
Found external IP:  x.x.x.x
Fetching Domain ID for: domain.com
Fetching Record ID for:  sub
Updating record sub . domain.com to x.x.x.x
Error:  **init**() got an unexpected keyword argument 'method'

**Comment by ryanwcraig** [comment]
Hi rerouted,

You don't happen to have a full stack trace, do you?

**Comment by rerouted** [comment]
Can you tell me how to provide that and I will.

-- 
Ryan Sullivan

On April 20, 2015 at 9:15:45 AM, Ryan Craig (notifications@github.com) wrote:

Hi rerouted,

You don't happen to have a full stack trace, do you?

**Comment by rerouted** [comment]
Does this help?

Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "updater-v2.py", line 89, in <module>
    set_record_ip(domain, record, ipaddr)
  File "updater-v2.py", line 70, in set_record_ip
    req = urllib.request.Request(url, data, headers, method='PUT')
TypeError: __init__() got an unexpected keyword argument 'method'
------------------------------------------------------------
Error:  __init__() got an unexpected keyword argument 'method'

**Comment by ryanwcraig** [comment]
It does! I'll get back to you once I look the code over.

**Comment by mike-polatoglou** [comment]
Had the same problem myself, it happens if your version of Python is 3.2 (In Python 3.2 the Request initializer doesn't have a method argument)

**Comment by dan142** [comment]
I too am having this problem. I've had a look, and I'm not 100% sure its even possible to make a PUT request using urllib on 3.2. I've worked around it by using the Python "Requests" library instead, but this is not ideal as it is not included as part of a standard Python installation and must be installed manually. Nonetheless, it's a great library and it's solved the issue with 3.2, for me at least.

**Comment by cmcqueen** [comment]
I've hit this issue, running Python 3.2.3 on a Raspberry Pi running an old version of Raspbian (from 2013 I reckon). Probably I can resolve this by upgrading my Raspberry Pi OS to a newer version.

**Comment by n3o-Bhushan** [comment]
code has a mistake, it should be methods and not method in the route 

ex - 
req = urllib.request.Request(url, data, headers, ** methods ** ='PUT')
