### ISSUE TITLE
[Interest Check] Email notification when IP address changes

### ISSUE THREAD

**Issue by ryanwcraig** [bensquire/Digital-Ocean-Dynamic-DNS-Updater#12]
I'm interested in this myself, and have no problem writing it, but I wanted to see if anyone else was too!

**Comment by mathieu-aubin** [comment]
Agreed it would make for a more complete tool. Assuming users have the option to toggle on/off notifications. Not having much experience in that area myself, i'm wondering what would be considered as a failsafe, aka 'miracle' solution for sending mail. Hosting a 'dropplet' doesn't always mean wanting to run a mail server, even just locally. Could DO possibly get involved? I might be out of my league here but hey, asking is proof of intelligence! - thanks for clarifying if you can.
