### ISSUE TITLE
Standardise PHP/Python usage

### ISSUE THREAD

**Issue by bensquire** [bensquire/Digital-Ocean-Dynamic-DNS-Updater#13]
@ryanwcraig I'm hoping you might be able to help... I'm in the process of updating the PHP script so that it accepts the parameters via the command line.

For example it will be triggered by calling:

    php updater-v2.php accessToken domain record

This way we don't need config files, and it makes sense that its triggered via the command line.

I could possibly change the python script myself, but I'm kinda hoping you might be able to help? You can find my current changes in the branch 'command-line-params'.

**Comment by ryanwcraig** [comment]
Absolutely! I was just doing something like this earlier in the week, so
shouldn't be too hard. I'll keep you posted.
