### ISSUE TITLE
Continuous Integration with Travis

### ISSUE THREAD

**Issue by ryanwcraig** [bensquire/Digital-Ocean-Dynamic-DNS-Updater#15]
What are everyone's thoughts on using continuous integration (like Travis) for testing builds/changes when they're made? It might also get this project some more exposure as they show recent runs!

**Comment by bensquire** [comment]
@ryanwcraig I'm up for this and its something I've been thinking on for the PHP code, but its going to involve a rewrite and take it from being "a script" into more of a library (classes, unit tests etc)

**Comment by ryanwcraig** [comment]
Yeah, that was my concern as well. I think the Python script is a good candidate right now (as long as it runs without hitting an error, the CI tests should pass, right?), but if it needs to be converted I can definitely look into that!

Actually, now that I think about it, Jenkins might require that each be in its own repo/project (I think).

**Comment by bensquire** [comment]
I’m not sure I follow…

In my head the curl responses would be mocked, we wouldn’t actually make requests to a DO box. In PHP I can deff inject a Curl mock, I’m assuming (maybe incorrectly) that can be done in Python?

**Comment by ryanwcraig** [comment]
You know, I completely forgot about the curl responses! Sorry, haven't quite had enough coffee yet today... 

It should be doable in Python, but I'll have to research that a bit further. Worst case, we could write tests for good data, bad data, etc.
