### ISSUE TITLE
ImportError: No module named request

### ISSUE THREAD

**Issue by orangeudav** [bensquire/Digital-Ocean-Dynamic-DNS-Updater#17]
```
> python updater.py xxx yyy.com zzz
Traceback (most recent call last):
  File "updater.py", line 7, in <module>
    import urllib.request
ImportError: No module named request
```
???

**Comment by ryanwcraig** [comment]
It looks like you're using Python v2.x - are you sure you're using v3?

**Comment by yorch** [comment]
If you are using OSX and Homebrew, you can install python 3 alongside python 2, just do:

    brew install python3

And run the script like:

    python3 updater.py ...
