### ISSUE TITLE
Does not work correctly when updating the apex (host @)

### ISSUE THREAD

**Issue by benjaminblack** [bensquire/Digital-Ocean-Dynamic-DNS-Updater#22]
The getRecord function loops through the *domain_records* array and returns the first record it finds where the *'name'* field matches, without checking that the *'type'* field is *'A'*. 

This is a problem when attempting to update the *@* host, because the Digital Ocean API returns the NS records before the A records for the *@* host in the domain_records array. (The *@* host is a self-reference to the apex domain, so it's used to update the A record for the domain itself, i.e. example.com.)

Therefore, attempting to update the A record for the *@* host results in clobbering the first NS record.

This is fixed in the PHP by simply adding a check on the record type:

    if ($record['name'] === RECORD && $record['type'] === 'A') {

**Comment by bensquire** [comment]
Thanks @benjaminblack apologies for the lack of action.
