### ISSUE TITLE
config

### ISSUE THREAD

**Issue by thisboyiscrazy** [bensquire/Digital-Ocean-Dynamic-DNS-Updater#6]
move the config into a file that is ignored by git so when I do a git pull I can keep my config.

**Comment by bensquire** [comment]
@thisboyiscrazy This is now working for python thanks to a fellow githubber. Do you use PHP?

**Comment by thisboyiscrazy** [comment]
No just python thanks.

**Comment by bensquire** [comment]
We've actually gone a slightly different route and these are now passed in as command line arguments. Either way you won't need to omit a file with your DO credentials.
