### ISSUE TITLE
Config info in another file

### ISSUE THREAD

**Issue by ryanwcraig** [bensquire/Digital-Ocean-Dynamic-DNS-Updater#9]
It might be worth allowing the user to put their API token/username/config info in another file (text file most likely), so that it doesn't need to be taken out of the source when committed.

**Comment by bensquire** [comment]
I completely agree! see #6 ... Biggest problem is I don't know python!

**Comment by ryanwcraig** [comment]
Ahh, didn't check those - sorry about that! Anyway, it's something I'd like to work on -- I'll make a pull request in a few days.
